apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-consumer-deployment
  labels:
    app: inference-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-consumer
  template:
    metadata:
      labels:
        app: inference-consumer
    spec:
      containers:
      - name: inference-consumer
        image: #TODO - make sure inference_consumer creates an image like 192.168.5.180:5000/ml-inference
        ports:
        - containerPort: 8501
        env:
        - name: MODEL_NAME
          value: inference-consumer