# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   minReadySeconds: 5

#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: 192.168.5.173:5000/kafka
#         ports:
#         - containerPort: 9092
#         env:
#         - name: KAFKA_ADVERTISED_LISTENERS
#           value: "PLAINTEXT://kafka-service:9092"
#         - name: KAFKA_BROKER_ID
#           value: "1"
#         - name: KAFKA_CREATE_TOPICS
#           value: images:1:1

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: strimzi/kafka:latest
        env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT"
          - name: KAFKA_LISTENER_NAME_PLAINTEXT_LISTENER
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_LISTENER_PORT
            value: "9092"
          - name: KAFKA_LOG4J_ROOT_LOGLEVEL
            value: "INFO"  # You can change this to DEBUG, ERROR, etc.
          - name: KAFKA_LOG4J_LOGGERS
            value: "kafka.network=DEBUG,kafka.log=DEBUG"  # Example of additional logging
        ports:
          - containerPort: 9092
