# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   minReadySeconds: 5

#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: 192.168.5.173:5000/kafka
#         ports:
#         - containerPort: 9092
#         env:
#         - name: KAFKA_ADVERTISED_LISTENERS
#           value: "PLAINTEXT://kafka-service:9092"
#         - name: KAFKA_BROKER_ID
#           value: "1"
#         - name: KAFKA_CREATE_TOPICS
#           value: images:1:1

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.0  # Use a compatible KRaft-mode Kafka image
        env:
          - name: KAFKA_PROCESS_ROLES
            value: "broker,controller"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@localhost:9093"  # Adjust for your setup
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service:9092"
          - name: KAFKA_LOG_DIRS
            value: "/var/lib/kafka/data"
        ports:
        - containerPort: 9092
        - containerPort: 9093
        volumeMounts:
          - name: kafka-data
            mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          emptyDir: {}
