---
  - name: Create a VM
    openstack.cloud.server:
      state: present
      security_groups:
        - default
        - ENABLE_SSH
        - ENABLE_ZOOKEEPER
      name: "Team17-1"
      image: "CC-Ubuntu22.04"
      flavor: "m1.medium"
      availability_zone: "nova"
      key_name: "team17-keypair"
      network: "CH-822922-net"
      auto_ip: false
      cloud: "CH-822922"
...