---
- name: Gather facts for Cloud VMs
  hosts: all
  gather_facts: no
  become: false

  tasks:
    - name: Retrieve VM information
      openstack.cloud.server_info:
        name: "{{ vm_prefix }}*"
        availability_zone: "{{ availability_zone }}"
        auth:
          cloud: "{{ cloud_name }}"
      register: vm_info

    - name: Set fact for private IP addresses of VMs
      set_fact:
        vm_private_ips: "{{ vm_info.results | map(attribute='private_v4') | list }}"

    - name: Debug output - private IP addresses
      debug:
        msg: "Private IP addresses of VMs: {{ vm_private_ips }}"
