---
  - name: Create a VM
    openstack.cloud.server:
      state: present
      security_groups:
        - default
        - ENABLE_SSH
        - ENABLE_ZOOKEEPER
      name: "{{ vm_prefix }}{{ item }}"
      image: "{{ image_name }}"
      flavor: "{{ vm_flavor }}"
      availability_zone: "{{ availability_zone }}"
      key_name: "{{ key }}"
      network: "{{ network_name }}"
      auto_ip: false
      cloud: "{{ cloud_name }}"
    loop: "{{ range(1, 5) }}"
...