---
  - name: Creates Apps directory
    ansible.builtin.file:
      path: ~/Apps
      state: directory
    become: yes

  - name: Unpack Kafka from local to VM
    ansible.builtin.unarchive:
        src: ~/tmp/kafka_2.13-3.6.2.tgz
        dest: '~/Apps'
        copy: no
    become: yes
