---
- name: Retrieve VM information
  openstack.cloud.server_info:
    cloud: "CH-822922"
    server: "Team17*"
  register: result

- name: Update Inventory with private IP addresses
  lineinfile:
    path: Inventory
    state: present
    insertafter: "# @@ inserthere"
    line: "{{ item.addresses['CH-822922-net'][0].addr }} ansible_python_interpreter=/usr/bin/python3"
  loop: "{{ result.servers }}"
  when: item.addresses is defined and 'CH-822922-net' in item.addresses

...
