apiVersion: batch/v1
kind: Job
metadata:
  name: iot-producer3
spec:
  template:
    metadata:
      labels:
        app: iot-producer3
    spec:
      containers:
      - name: iot-producer3
        image: 192.168.1.81:5000/iot-producer
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["python3 iot_producer_docker.py iot_producer_3 && sleep 3600"]
      restartPolicy: Never