apiVersion: batch/v1
kind: Job
metadata:
  name: iot-producer1
  namespace: team17
spec:
  template:
    metadata:
      labels:
        app: iot-producer1
    spec:
      containers:
      - name: iot-producer1
        image: 192.168.1.81:5000/team17/iot-producer
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["python3 iot_producer_docker.py iot_producer_two_1 && sleep 3600"]
      restartPolicy: Never
