apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
spec:
  type: ClusterIP # Options: ClusterIP (default, internal access), NodePort (external access), LoadBalancer
  ports:
    - port: 5984 # Default port for couchDB;
      targetPort: 5984 # Matches the database container port
      protocol: TCP
  selector:
    app: database # This should match the label in your database deployment
