---
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install transport
    apt:
      name: apt-transport-https
      state: latest

  - name: Install certificates
    apt:
      name: ca-certificates
      state: latest

  - name: Install curl
    apt:
      name: curl
      state: latest
  
  - name: Install gpg
    apt:
      name: gpg
      state: latest

  - name: Create directory with permissions
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  - name: Add gpg key
    ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Update Apt Repository with K8s Sources
    lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
      create: yes

  - name: Update apt cache
    apt:
      update_cache: yes
      
  - name: Install kubelet
    apt:
      name: kubelet
      state: latest

  - name: Install kubeadm
    apt:
      name: kubeadm
      state: latest

  - name: Install kubectl
    apt:
      name: kubectl
      state: latest

  - name: Hold packages
    ansible.builtin.shell: apt-mark hold kubelet kubeadm kubectl

  - name: Enable kubelet
    systemd:
      name: kubelet
      enabled: true
      state: started

  - name: Add IPv4 forwarding
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: net.ipv4.ip_forward = 1

  - name: Enable IPv4
    ansible.builtin.shell: sudo sysctl --system

...