---
  - name: Creates tmp directory
    ansible.builtin.file:
      path: ~/tmp
      state: directory
    become: no

  - name: Download Kafka
    ansible.builtin.get_url:
        url: 'https://downloads.apache.org/kafka/3.7.1/kafka_2.13-3.7.1.tgz'
        dest: ~/tmp/kafka_2.13-3.7.1.tgz
    become: no