apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-consumer
  namespace: team17
  labels:
    app: database-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-consumer
  template:
    metadata:
      labels:
        app: database-consumer
    spec:
      containers:
      - name: database-consumer
        image: 192.168.1.81:5000/team17/database-consumer