apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: team17
spec:
  replicas: 1
  serviceName: kafka
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: 192.168.1.81:5000/team17/kafka
        env:
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: POD_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-0.kafka.team17.svc.cluster.local:9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_PORT
            value: "9092"
        ports:
          - containerPort: 9092
        volumeMounts:
          - name: log4j-config
            mountPath: /opt/kafka/custom-config/log4j.properties
            subPath: log4j.properties
      volumes:
        - name: log4j-config
          configMap:
            name: log4j-config