apiVersion: batch/v1
kind: Job
metadata:
  name: iot-producer3
spec:
  template:
    metadata:
      labels:
        app: iot-producer3
    spec:
      containers:
      - name: iot-producer3
        image: 192.168.5.173:5000/iot-producer
        imagePullPolicy: Always
        command: ["python3"]
        args: ["iot_producer_docker.py", "iot_producer_3"] 
      restartPolicy: Never