---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose: 
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#

#####################################################
### Play 6: Download and Install Kafka on our Cloud VMs
#
#####################################################

# @@ My suggestion is that instead of each VM downloading the
#    entire kafka distribution, we could download it locally
#    on the controller machine.
# 
#    Subsequently, we then copy the *.tgz file to each VM where
#    we untar and uncompress it @@
- name: "Play 6a - Download kafka locally"
  hosts: LocalMC  # specified in the Inventory file
  remote_user:  "{{ local_user }}"      # note that the user is cc on Chameleon
  gather_facts: no
  become: false  # no need here.
  collections:
  - ansible-base

  tasks:    # the task to be performed
  # @@ You have to write the following child playbook @@
  - import_tasks: tasks/playbook_download_kafka.yaml

- name: "Play 6b - Install Kafka on Cloud VMs"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  hosts: CloudVMs          # specified in the Inventory file
  remote_user:  "{{ cloud_user }}"      # note that the user is cc on Chameleon
  gather_facts: no
  become: false  # we set it per task
  collections:
  - ansible-base

  tasks:    # the task to be performed
  # @@ You have to write the following child playbook @@
  - import_tasks: tasks/playbook_install_kafka.yaml

#####################################################
### Play 7: Set firewalld rules
#####################################################

- name: "Play 7 - Handle Firewalld policies"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: true  # we set it here instead of doing per task unless
                # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
  - ansible-base
  - community.general

  tasks:    # the task to be performed
  - import_tasks: tasks/playbook_set_firewalld_rules.yaml

#####################################################
### Play 8: Install K8s
#####################################################

- name: "Play 8 - Install K8s"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: true  # we set it here instead of doing per task unless
                # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
  - ansible-base
  - community.general

  tasks:    # the task to be performed
  - import_tasks: tasks/playbook_install_k8s.yaml

#####################################################
### Play 9: Update config.toml
#####################################################

- name: "Play 9 - Update config.toml"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: true  # we set it here instead of doing per task unless
                # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
  - ansible-base
  - community.general

  tasks:    # the task to be performed
  - import_tasks: tasks/playbook_update_config.yaml

#####################################################
### Play 10: Configure Docker Private Registry
#####################################################

- name: "Play 10 - Configure Docker Private Registry"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: true  # we set it here instead of doing per task unless
                # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
  - ansible-base
  - community.general

  tasks:    # the task to be performed
  - import_tasks: tasks/playbook_configure_private_docker.yaml
  
...

