---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose: 
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#

#####################################################
### Play 10: Configure Docker Private Registry
#####################################################

- name: "Play 10 - Configure Docker Private Registry"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: true  # we set it here instead of doing per task unless
                # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
  - ansible-base
  - community.general

  tasks:    # the task to be performed
  - import_tasks: tasks/playbook_configure_private_docker.yaml
  
...

