apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: team17
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - name: database
      protocol: TCP
      port: 5984
      targetPort: 5984