apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: team17
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092