apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: team17
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  clusterIP: None
