apiVersion: batch/v1
kind: Job
metadata:
  name: trading-bot1
spec:
  template:
    metadata:
      labels:
        app: trading-bot1
    spec:
      containers:
      - name: exchange
        image: 192.168.5.245:5000/trading-bot1
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["pip3 install --upgrade kafka-python && pip3 install six && python3 trading-bot1-docker.py"]
      restartPolicy: Never