---
apiVersion: batch/v1
kind: Job
metadata:
  name: trading-bot2
spec:
  template:
    metadata:
      labels:
        app: trading-bot2
    spec:
      containers:
        - name: trading-bot2
          image: 192.168.5.145:5000/trading-bot2
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args: ["python3 trading-bot2-docker.py"]
      restartPolicy: Never
